import type { SuggestDoctorsForHRInput } from "@/ai/flows/suggest-doctors-for-hr";

export const doctorProfiles: SuggestDoctorsForHRInput['doctorProfiles'] = [
  {
    name: "Dr. Maria Dela Cruz",
    specialization: "Cardiology",
    residency: "Philippine Heart Center",
    fellowship: "Cardiovascular Disease, St. Luke's Medical Center",
    affiliations: "Makati Medical Center, St. Luke's Medical Center - Global City",
    city: "Makati",
    province: "Metro Manila",
    availableFor: ["Full-time", "Referrals"],
    bio: "Experienced cardiologist with a focus on interventional cardiology. Passionate about patient care and clinical research.",
  },
  {
    name: "Dr. Juanito Reyes",
    specialization: "Pediatrics",
    residency: "Philippine General Hospital",
    fellowship: "Pediatric Pulmonology, National Children's Hospital",
    affiliations: "The Medical City, Asian Hospital and Medical Center",
    city: "Muntinlupa",
    province: "Metro Manila",
    availableFor: ["Full-time", "Telemed"],
    bio: "Dedicated pediatrician with a subspecialty in pediatric pulmonology. Committed to providing comprehensive care for children.",
  },
  {
    name: "Dr. Anna Lim",
    specialization: "Dermatology",
    residency: "Jose R. Reyes Memorial Medical Center",
    affiliations: "Belo Medical Group, Aivee Clinic",
    city: "Cebu City",
    province: "Cebu",
    availableFor: ["Full-time", "Referrals", "Telemed"],
    bio: "Aesthetic and clinical dermatologist specializing in advanced skin treatments and cosmetic procedures.",
  },
  {
    name: "Dr. Carlos Santos",
    specialization: "Orthopedic Surgery",
    residency: "University of Santo Tomas Hospital",
    affiliations: "St. Luke's Medical Center - Quezon City",
    city: "Quezon City",
    province: "Metro Manila",
    availableFor: ["Locum", "Referrals"],
    bio: "Orthopedic surgeon specializing in sports injuries and joint replacement. Available for locum duties on weekends.",
  },
  {
    name: "Dr. Elena Garcia",
    specialization: "Family Medicine",
    residency: "Makati Medical Center",
    affiliations: "Kaiser Medical Center, Hi-Precision Diagnostics",
    city: "Davao City",
    province: "Davao del Sur",
    availableFor: ["Locum", "Telemed"],
    bio: "Family physician focused on preventive care and managing chronic illnesses. Strong advocate for telemedicine.",
  },
];


export const jobPosts = [
  {
    title: "Consultant Cardiologist",
    type: "Permanent",
    specialty: "Cardiology",
    location: "Makati, Metro Manila",
    hospital: "Makati Medical Center",
    contact: "hr@makatimed.net.ph",
  },
  {
    title: "Pediatrician for Weekend Duties",
    type: "Locum",
    specialty: "Pediatrics",
    location: "Quezon City, Metro Manila",
    hospital: "St. Luke's Medical Center",
    contact: "careers@stlukes.com.ph",
  },
  {
    title: "Telemedicine Dermatologist",
    type: "Telemed",
    specialty: "Dermatology",
    location: "Remote",
    hospital: "KonsultaMD",
    contact: "partner@konsulta.md",
  },
  {
    title: "Orthopedic Surgery Fellow",
    type: "Fellowship",
    specialty: "Orthopedic Surgery",
    location: "Muntinlupa, Metro Manila",
    hospital: "Asian Hospital and Medical Center",
    contact: "academics@asianhospital.com",
  },
   {
    title: "General Physician",
    type: "Permanent",
    specialty: "Family Medicine",
    location: "Cebu City, Cebu",
    hospital: "Chong Hua Hospital",
    contact: "hr@chonghua.com.ph",
  },
  {
    title: "ER Physician (Locum)",
    type: "Locum",
    specialty: "Emergency Medicine",
    location: "Davao City, Davao del Sur",
    hospital: "Davao Doctors Hospital",
    contact: "recruitment@ddh.com.ph",
  },
];

export const messages = [
  {
    id: 1,
    name: "Dr. Juanito Reyes",
    avatar: "https://placehold.co/100x100.png",
    lastMessage: "Thank you for the referral, Dr. Maria. The patient is scheduled for consultation next week.",
    timestamp: "10:45 AM",
    unread: 0,
  },
  {
    id: 2,
    name: "HR - Makati Med",
    avatar: "https://placehold.co/100x100.png",
    lastMessage: "Hi Dr. Santos, are you available for an interview regarding the Orthopedics post?",
    timestamp: "9:30 AM",
    unread: 2,
  },
  {
    id: 3,
    name: "Dr. Anna Lim",
    avatar: "https://placehold.co/100x100.png",
    lastMessage: "Great to connect! I saw your post on the bulletin about the new laser equipment.",
    timestamp: "Yesterday",
    unread: 0,
  },
];
